# Generated by Django 4.2.11 on 2024-04-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge2food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredient',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
