# Generated by Django 5.0.5 on 2024-05-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge2food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeID',
            field=models.IntegerField(),
        ),
    ]
