# Generated by Django 5.0.3 on 2024-04-18 22:25

import annoying.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fridge2food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridge",
            name="owner",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
