# Generated by Django 5.0.3 on 2024-05-03 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fridge2food", "0002_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
