# Generated by Django 4.2.11 on 2024-04-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge2food', '0002_alter_fridgeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fridge2food.ingredient'),
            preserve_default=False,
        ),
    ]
