# Generated by Django 5.0.5 on 2024-05-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge2food', '0002_alter_recipe_recipeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeID',
            field=models.IntegerField(unique=True),
        ),
    ]
