# Generated by Django 5.0.4 on 2024-04-18 23:31

import annoying.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge2food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='owner',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeID',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
