# Generated by Django 5.0.4 on 2024-04-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge2food', '0002_alter_fridge_owner_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(default='ph.com'),
        ),
    ]
